{ options, config, pkgs, lib, ... }:

with lib;
{
  options = {
    modules.shell.zsh = with types; {
      enable = mkEnableOption "zsh";
      aliasFiles = mkOption { type = (listOf (either str path)); default = []; };
      envFiles = mkOption { type = (listOf (either str path)); default = []; };
    };
  };

  config = mkIf config.modules.shell.zsh.enable {
    users.defaultUserShell = pkgs.zsh;
    environment.systemPackages = [ pkgs.zsh ];

    # Required for zsh to conform to XDG. Avoids boostrap problem?
    environment.variables = {
      ZDOTDIR = "$XDG_CONFIG_HOME/zsh";
      ZSH_CACHE = "$XDG_CACHE_HOME/zsh";
    };

    home.configFile = {
      "zsh" = {
        source = "${config.local.configDir}/zsh";
        recursive = true;
      };
      "zsh/extra_aliases.sh".text = ''
        # This file was autogenerated with Nix, and may be overwritten!
        ${strings.concatMapStrings (path: "source '${path}'\n") config.modules.shell.zsh.aliasFiles}
      '';
      "zsh/extra_environment.sh".text = ''
        # This file was autogenerated with Nix, and may be overwritten!
        ${strings.concatMapStrings (path: "source '${path}'\n") config.modules.shell.zsh.envFiles}
      '';
    };
  };
}
