export DOTFILES=$HOME/dotfiles
export ZSH=$DOTFILES/zsh

ZSH_THEME='simple'
plugins=(git)

source $ZSH/oh-my-zsh.sh
source $ZSH/aliases.sh
source $ZSH/environment.sh

if [[ "$OSTYPE" == "darwin"* ]]; then
  source $ZSH/mac-specific.sh
fi
